build:
    componentize-py \
        --wit-path wit \
        --world plugin \
        --world-module plugin \
        componentize \
        app \
        -o plugin.wasm

generate-bindings:
    componentize-py \
        --wit-path wit \
        --world plugin \
        --world-module plugin \
        bindings \
        plugin

