package wassel:plugin;

interface http-plugin {
    use wasi:http/types@0.2.3.{incoming-request, response-outparam};

    resource handler {
        handle: func(
            request: incoming-request,
            response-out: response-outparam
        );
    }

    record endpoint {
        path: string,
        handler: handler,
    }

    record plugin {
        /// The name of the plugin. Must be kebab-case with all letters lowercase,
        /// e.g. "hello-plugin".
        name: string,

        /// Version of the plugin in SemVer format.
        version: string,

        /// Short description of the plugin
        description: option<string>,

        /// List of plugin endpoints
        endpoints: list<endpoint>,
    }

    instantiate: func() -> plugin;
}

world exports {
    export http-plugin;
}
