package hello:plugin;

world plugin {
    include wassel:plugin/exports;

    use wasi:http/types@0.2.3.{incoming-request, response-outparam};

    export handle-root: func(
        request: incoming-request,
        response-out: response-outparam
    );
}
